name: urban-sound-py38
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - click=8.1.7
  - cryptography=43.0.0
  - flatbuffers=23.5.26
  - frozenlist=1.4.1
  - gast=0.5.5
  - giflib=5.2.2
  - google-auth=2.35.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - grpcio=1.54.3
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - keras=2.13.1
  - krb5=1.21.3
  - libabseil=20230125.3
  - libaec=1.1.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgrpc=1.54.3
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=3.21.12
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markdown=3.6
  - markupsafe=2.1.5
  - multidict=6.0.5
  - ncurses=6.5
  - numpy=1.24.4
  - oauthlib=3.2.2
  - openssl=3.5.1
  - opt_einsum=3.4.0
  - packaging=25.0
  - protobuf=4.21.12
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pyjwt=2.9.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-flatbuffers=24.3.25
  - python_abi=3.8
  - pyu2f=0.1.5
  - re2=2023.03.02
  - readline=8.2
  - requests-oauthlib=2.0.0
  - rsa=4.9
  - setuptools=75.3.0
  - snappy=1.1.10
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.13.1
  - tensorflow-base=2.13.1
  - tensorflow-estimator=2.13.1
  - termcolor=2.4.0
  - tk=8.6.13
  - typing_extensions=4.5.0
  - urllib3=2.2.3
  - werkzeug=3.0.6
  - wheel=0.45.1
  - wrapt=1.16.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yarl=1.9.4
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - appnope==0.1.4
      - attrs==25.3.0
      - audioread==3.0.1
      - backcall==0.2.0
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.57.0
      - importlib-resources==6.4.5
      - inflate64==1.0.0
      - ipython==7.34.0
      - jams==0.3.5
      - jedi==0.19.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.41.1
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.7
      - mir-eval==0.8.2
      - msgpack==1.1.1
      - multivolumefile==0.2.3
      - numba==0.58.1
      - pandas==1.5.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==25.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - py7zr==0.22.0
      - pybcj==1.0.2
      - pycryptodomex==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pyppmd==1.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzstd==0.17.0
      - referencing==0.35.1
      - requests==2.32.4
      - rpds-py==0.20.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - six==1.17.0
      - sortedcontainers==2.4.0
      - soundata==1.0.1
      - soundfile==0.13.1
      - soxr==0.3.7
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wcwidth==0.2.13
      - zipp==3.20.2
